import { Inter } from "next/font/google";
import "../globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
  
} from '@clerk/nextjs'
import {
  AppBar,
  Button,
  Toolbar,
  Typography,
} from "@mui/material";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Flashcard SaaS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<ClerkProvider>
    <html lang="en">

      
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
